name: Bicep_deployment
run-name: Bicep_deployment triggered by ${{ github.event_name }}

on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  bicepfilePath: ./deployments/prd/
  deploymentRegion: westeurope

jobs:
  buildtest:
    runs-on: ubuntu-latest
    name: 'Build & Test'
    steps:
        # Checkout the repository
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      - name: Validate Bicep file
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az deployment sub validate --template-file ${{ env.bicepfilePath }}main.bicep --location ${{ env.deploymentRegion }}
      - name: What-If bicep deployment
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az deployment sub create --what-if --template-file ${{ env.bicepfilePath }}main.bicep --location ${{ env.deploymentRegion }}
# to do: add approval step  
  deploy:
    runs-on: ubuntu-latest
    needs: [buildtest]
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: Azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
      - name: Deploy bicep to Azure
        uses: Azure/cli@v2
        with:
          inlineScript: |
                az deployment sub create --template-file  ${{ env.bicepfilePath }}main.bicep --location ${{ env..deploymentRegion }}
